#pragma config(Sensor, port3,  horizontalGyro, sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  Led,            sensorVexIQ_LED)
#pragma config(Sensor, port8,  ColorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  LED2,           sensorVexIQ_LED)
#pragma config(Sensor, port12, bumper,         sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          armLiftLeft,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armLiftRight,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         armLiftTop,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat(forever)
	{
		tankControl(ChD,ChA,10);

		if(getJoystickValue(BtnLUp)==1) //AKA true
		{
			setMultipleMotors(100,armLiftLeft,armLiftRight,armLiftTop);
		}


		if(getJoystickValue(BtnLDown)==1)
		{
			setMultipleMotors(-80,armLiftLeft,armLiftRight,armLiftTop);

		}

		if((getJoystickValue(BtnLUp)==0) && (getJoystickValue(BtnLDown)==0))
		{
			stopMultipleMotors(armLiftLeft,armLiftRight,armLiftTop);
		}

		armControl(slideMotor,BtnRUp,BtnRDown);

	sleep(1);

		}  //repeat end





}
