#pragma config(Sensor, port3,  horizontalGyro, sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  Led,            sensorVexIQ_LED)
#pragma config(Sensor, port8,  colorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  LED2,           sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          armLift2,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armLift,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int  CalibrateGYROS(tSensors nGyro1,TI2CGyroCalibrateSamples nCalibrationSetting){
	/*
	Calibration of GYROS appears to be neccessary at the begining of any program
	where you are going to make use of a GYRO. The amount of time to complete the
	calibration process varys based on the number of samples specified.

	During calibration the robot mus be kept prefectly still.
	So we are going to wait a bit before starting calibration to
	insure know one is touching the robot.
	*/

	string str;

	displayString(1,"Calibrating Gyro....");
	sleep(2000);
	stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
	//stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);

	/*This actually begins the gyro calibration process*/
	startGyroCalibration(nGyro1, nCalibrationSetting);
	//startGyroCalibration(nGyro2, nCalibrationSetting);

	sleep(10); //This appears to be need for debug but doesn't hurt anything.

	/*Loop until the calibration process is complete on both GYROS*/
	//while(getGyroCalibrationFlag(nGyro1)||getGyroCalibrationFlag(nGyro2))
	while(getGyroCalibrationFlag(nGyro1))
	{
		stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
		//	stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);
		sleep(10);
	}
	/*###########################################
	*# GYRO Calibration is complete.
	*###########################################*/
	return 0;
}

bool PickUpRings()
{
	setTouchLEDColor(LED2,colorViolet);

	waitUntil(getTouchLEDValue(LED2)==true);

	setTouchLEDColor(LED2,colorGreen);

	resetGyro(horizontalGyro);

	forward(740,degrees,75); //Moving forward to blue rings.

	repeatUntil(getGyroDegrees(horizontalGyro)<=-80) //Spinnig so clamps are pointed at blue peg.
	{
		setMotor(leftMotor,50);

		setMotor(rightMotor,-50);
	}
	stopAllMotors();

	backward(255,degrees,75); //Backing up into blue rings

	sleep(750);

	forward(400,milliseconds,25);

	stopAllMotors();

	setMotor(armLift,-100);

	setMotor(armLift2,100);

	sleep(1000);

	setMotorBrakeMode(armLift,motorHold);

	setMotorBrakeMode(armLift2,motorHold);

	forward(225,75); //Away from rings before spinning

	stopAllMotors();

	resetGyro(horizontalGyro);

	repeatUntil(getGyroDegrees(horizontalGyro)>=170) //Turning so that the ring clamps are facing the poles.
	{
		setMotor(leftMotor,-50);

		setMotor(rightMotor, 50);

	}
	stopAllMotors();

	setMotor(armLift,-100); //Lifting the ARM up because it tends to lower down

	setMotor(armLift2,100);

	sleep(1000);

	setMotorBrakeMode(armLift,motorHold);

	setMotorBrakeMode(armLift2,motorHold);

	stopAllMotors();

	setMotor(slideMotor,-100); //sliding so that the ring clamp is on par with the pole.

	sleep(400);

	stopAllMotors();

	repeatUntil(getGyroDegrees(horizontalGyro)>=170) //Turning so that the ring clamps are facing the poles.
	{
		setMotor(leftMotor,-50);

		setMotor(rightMotor, 50);
	}
	stopAllMotors();

	backward(1000,degrees,100); //Backing up to put rings on pole.

	stopAllMotors();

	setMotor(armLift,20);

	setMotor(armLift2,-20);

	sleep(1500);

	stopAllMotors();

	forward(360,degrees,100); //Pulling away so that the robot isn't touching the rings.

	setTouchLEDColor(Led,colorRed);

	return true;
}


task main()
{
	setTouchLEDColor(Led,colorRed);


	setTouchLEDColor(Led,colorBlue);

	waitUntil(getTouchLEDValue(Led)==true);

	setMotor(slideMotor,100);

	forward(6000, milliseconds,100);

	stopAllMotors();

	setMotor(slideMotor,-100);

	sleep(750);

	stopAllMotors();

	forward(950,milliseconds,50);

	sleep(500);

	backward(500,milliseconds,50);

	setMotor(slideMotor,-100);

	sleep(1100);

	stopAllMotors();

	forward(650,milliseconds,50);

	backward(700,milliseconds,100);

	setMotorBrakeMode(leftMotor,motorCoast);
	setMotorBrakeMode(rightMotor,motorCoast);
	setMotorBrakeMode(armLift2,motorCoast);
	setMotorBrakeMode(armLift,motorCoast);
	setMotorBrakeMode(slideMotor,motorCoast);

	//PickUpRings();

}
