#pragma config(Sensor, port2,  distance,       sensorVexIQ_Distance)
#pragma config(Sensor, port3,  horizontalGyro, sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  Led,            sensorVexIQ_LED)
#pragma config(Sensor, port8,  ColorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armLift,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int  CalibrateGYROS(tSensors nGyro1,TI2CGyroCalibrateSamples nCalibrationSetting){
	/*
	Calibration of GYROS appears to be neccessary at the begining of any program
	where you are going to make use of a GYRO. The amount of time to complete the
	calibration process varys based on the number of samples specified.

	During calibration the robot mus be kept prefectly still.
	So we are going to wait a bit before starting calibration to
	insure know one is touching the robot.
	*/

	string str;

	displayString(1,"Calibrating Gyro....");
	sleep(2000);
	stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
	//stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);

	/*This actually begins the gyro calibration process*/
	startGyroCalibration(nGyro1, nCalibrationSetting);
	//startGyroCalibration(nGyro2, nCalibrationSetting);

	sleep(10); //This appears to be need for debug but doesn't hurt anything.

	/*Loop until the calibration process is complete on both GYROS*/
	//while(getGyroCalibrationFlag(nGyro1)||getGyroCalibrationFlag(nGyro2))
	while(getGyroCalibrationFlag(nGyro1))
	{
		stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
		//	stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);
		sleep(10);
	}
	/*###########################################
	*# GYRO Calibration is complete.
	*###########################################*/
	return 0;
}

task main()
{
	//This is calibrating the gyros.
	setTouchLEDColor(Led,colorRed);

	CalibrateGYROS(horizontalGyro,gyroCalibrateSamples4096);
	//	setGyroSensitivity(horizontalGyro,gyroHighSensitivity);
	setTouchLEDColor(Led,colorYellow);

	waitUntil(getTouchLEDValue(Led)== 1);

	resetGyro(horizontalGyro);

	forward(750, degrees, 75);



	repeatUntil(getGyroDegrees(horizontalGyro) <= -80)
	{
		setMotorSpeed(leftMotor,50);
	setMotorSpeed(rightMotor,-50);
	}
	stopMultipleMotors(leftMotor, rightMotor);

	backward(360, degrees, 75);
	setTouchLEDColor(Led, colorBlue);
	setMotorSpeed(rightMotor,20);
	setMotorSpeed(leftMotor,20);
	sleep(100);
	stopMultipleMotors(rightMotor,leftMotor);

	setMotorSpeed(armLift, -100);
	sleep(1000);
	stopAllMotors();
	setMotorBrakeMode(armLift, motorHold);

	forward(360, degrees, 100);

	resetGyro(horizontalGyro);

	if (getGyroDegrees(horizontalGyro)==0)
	{
		setTouchLEDColor(Led, colorBlue);
}

	repeatUntil(getGyroDegrees(horizontalGyro) >= 170)
	{
		setMotorSpeed(leftMotor,-50);
	setMotorSpeed(rightMotor,50);
	sleep(2);
	}
	stopAllMotors();

  setMotor(slideMotor, 100);
  sleep(700);
  stopAllMotors();
  setMotorSpeed(armLift, -100);
  sleep(200);
  setMotorBrakeMode(armLift, motorHold);
  stopAllMotors();
	backward(565, degrees, 75);
	setMotorSpeed(armLift, 100);
	sleep(1000);
	stopAllMotors();
	forward(360,degrees, 100);

	setTouchLEDColor(Led, colorGreen);

	waitUntil(getTouchLEDValue(Led)== 1);

	resetGyro(horizontalGyro);

	forward(750, degrees, 75);
}
