#pragma config(Sensor, port2,  leftLED,        sensorVexIQ_LED)
#pragma config(Sensor, port3,  rightLED,       sensorVexIQ_LED)
#pragma config(Sensor, port7,  horizontalGyro, sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armLift,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int  CalibrateGYROS(tSensors nGyro1,TI2CGyroCalibrateSamples nCalibrationSetting){
	/*
	Calibration of GYROS appears to be neccessary at the begining of any program
	where you are going to make use of a GYRO. The amount of time to complete the
	calibration process varys based on the number of samples specified.

	During calibration the robot mus be kept prefectly still.
	So we are going to wait a bit before starting calibration to
	insure know one is touching the robot.
	*/

	string str;

	displayString(1,"Calibrating Gyro....");
	sleep(2000);
	stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
	//stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);

	/*This actually begins the gyro calibration process*/
	startGyroCalibration(nGyro1, nCalibrationSetting);
	//startGyroCalibration(nGyro2, nCalibrationSetting);

	sleep(10); //This appears to be need for debug but doesn't hurt anything.

	/*Loop until the calibration process is complete on both GYROS*/
	//while(getGyroCalibrationFlag(nGyro1)||getGyroCalibrationFlag(nGyro2))
	while(getGyroCalibrationFlag(nGyro1))
	{
		stringFormat(str, "Gyro1CaliFlag: %d", getGyroCalibrationFlag(nGyro1)); displayString(2, str);
		//	stringFormat(str, "Gyro2CaliFlag: %d", getGyroCalibrationFlag(nGyro2)); displayString(3, str);
		sleep(10);
	}
	/*###########################################
	*# GYRO Calibration is complete.
	*###########################################*/
	return 0;
}


task main()
{
	//This is calibrating the gyros.
	CalibrateGYROS(horizontalGyro,gyroCalibrateSamples4096);

	// Raise armLift motor to highest position
	moveMotor(armLift,1370,milliseconds,100 );
	setMotorBrakeMode(armLift,motorHold);

	//Wait for user input to move forward
	setTouchLEDColor(leftLED,colorGreen);
	waitUntil(getTouchLEDValue(leftLED)== 1);

	//move forward 6 seconds
	int iHeading = 0;
	resetGyro(horizontalGyro);
	resetTimer(T1);
	while (getTimer(T1,milliseconds)<6100) ///Do this for 6.1 seconfds
	{
		iHeading = getGyroHeading(horizontalGyro);
		if (iHeading < 4 && iHeading > -4)  ///This like its going straight
		{
			setMotor(leftMotor, 100);
			sleep(1);
			setMotor(rightMotor, 100);
			sleep(1);
		}
		else if (iHeading >=4) { //ITs veering off to the right
			stopMotor(leftMotor);
			sleep(1);
			setMotor(rightMotor, 20);
			sleep(1);
		}
		else{ //its veering off to left
			stopMotor(rightMotor);
			sleep(1);
			setMotor(leftMotor, 20);
			sleep(1);
		}


	} // end while loop
	stopMotor(rightMotor);
	sleep(1);
	stopMotor(leftMotor);
	sleep(1);

	//	forward(6000,milliseconds,100);

	//slide right 0.25 seconds
	moveMotor(slideMotor, 250, milliseconds, -30);

	//move forward .45 seconds
	forward(450, milliseconds, 100);

	//move backward .30 seconds
	backward(300,milliseconds, 100);


	//slide left 1.3 seconds
	moveMotor(slideMotor, 1300, milliseconds, 50);

	//move forward .30 seconds
	forward(450, milliseconds, 100);

	//alert driver that program has completed
	setTouchLEDColor(leftLED,colorRed);
	//END








	displayString(2,"Rest Khan2.0");

	waitUntil(getTouchLEDValue(leftLED)== 1);


	/*ThisgetColorGrayscale(nDeviceIndex);
         actually begins the gyro calibration process*/
	startGyroCalibration(nGyro1, nCalibrationSetting);
	//startGyroCalibration(nGyro2, nCalibrationSetting);

	forward(500, milliseconds, 99);




}
