
#pragma config(Sensor, port2,  distance,       sensorVexIQ_Distance)
#pragma config(Sensor, port3,  rightLED,       sensorNone)
#pragma config(Sensor, port7,  horizontalGyro, sensorNone)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         armLift,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{
resetGyro


{	DisplayString("Reseting Gyro");
	Wait(getTouchLEDValue(3)>1;}

	gy=getGyroDegrees(7);

	if (gy>-4 || <4 )

	{
   setMultipleMotors(90, 1, 6,);}

   else (gy>4

 {setMotor(6, 80);}

 else if










