#pragma config(Sensor, port2,  distance,       sensorVexIQ_Distance)
#pragma config(Sensor, port3,  horizontalGyro, sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  Led,            sensorVexIQ_LED)
#pragma config(Sensor, port8,  ColorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          slideMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         armLift,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
